import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Button, Card, Input, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@esal/ui';
import { Link } from 'react-router-dom';
export default function LoginPage() {
    const [loginType, setLoginType] = useState('innovator');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const handleSubmit = (e) => {
        e.preventDefault();
        // TODO: Implement authentication
        console.log('Login attempted:', { loginType, email, password });
    };
    return (_jsx("div", { className: "min-h-screen bg-background flex items-center justify-center", children: _jsxs("div", { className: "w-full max-w-md", children: [_jsxs("div", { className: "text-center mb-8", children: [_jsx(Link, { to: "/", className: "text-3xl font-bold text-primary", children: "ESAL Platform" }), _jsx("p", { className: "text-muted-foreground mt-2", children: "Sign in to your account" })] }), _jsxs(Card, { className: "p-8", children: [_jsxs("form", { onSubmit: handleSubmit, className: "space-y-6", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium mb-2", children: "Account Type" }), _jsxs(Select, { value: loginType, onValueChange: (value) => setLoginType(value), children: [_jsx(SelectTrigger, { children: _jsx(SelectValue, {}) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "innovator", children: "Innovator Portal" }), _jsx(SelectItem, { value: "investor", children: "Investor Portal" }), _jsx(SelectItem, { value: "hub", children: "Hub/Accelerator Portal" })] })] })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium mb-2", children: "Email" }), _jsx(Input, { type: "email", required: true, value: email, onChange: (e) => setEmail(e.target.value), placeholder: "your@email.com" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium mb-2", children: "Password" }), _jsx(Input, { type: "password", required: true, value: password, onChange: (e) => setPassword(e.target.value), placeholder: "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022" })] }), _jsx(Button, { type: "submit", className: "w-full", children: "Sign In" })] }), _jsx("div", { className: "mt-6 text-center", children: _jsxs("p", { className: "text-sm text-muted-foreground", children: ["Don't have an account?", ' ', loginType === 'innovator' ? (_jsx(Link, { to: "/innovator", className: "text-primary hover:underline", children: "Get started as an innovator" })) : (_jsx(Link, { to: "/contact", className: "text-primary hover:underline", children: "Request access" }))] }) }), (loginType === 'investor' || loginType === 'hub') && (_jsx("div", { className: "mt-4 p-4 bg-muted rounded-lg", children: _jsxs("p", { className: "text-sm text-muted-foreground", children: [_jsx("strong", { children: "Note:" }), " ", loginType === 'investor' ? 'Investor' : 'Hub/Accelerator', " accounts require backend approval. Please ", _jsx(Link, { to: "/contact", className: "text-primary hover:underline", children: "contact us" }), " to request access."] }) }))] }), _jsx("div", { className: "text-center mt-6", children: _jsx(Link, { to: "/", className: "text-sm text-muted-foreground hover:text-foreground", children: "\u2190 Back to homepage" }) })] }) }));
}
