services:
  - type: static_site
    name: esal-investor-portal
    staticSiteGenerator: vite
    buildCommand: cd ../.. && pnpm install && pnpm turbo build --filter=investor-portal
    publishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: esal-platform-api
          property: host
        # Will resolve to https://your-api-name.onrender.com
      - key: VITE_SUPABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: VITE_SUPABASE_ANON_KEY
        sync: false  # Set manually in Render dashboard
      - key: VITE_APP_TITLE
        value: "ESAL Investor Portal"
      - key: VITE_ENVIRONMENT
        value: "production"
    buildFilter:
      paths:
        - apps/investor-portal/**
        - packages/**
        - pnpm-lock.yaml
        - turbo.json
      ignoredPaths:
        - "*.md"
        - "*.txt"