services:
  - type: static_site
    name: esal-platform-landing
    buildCommand: npm install -g pnpm@latest && cd ../.. && rm -rf node_modules && rm -rf apps/*/node_modules && pnpm install --frozen-lockfile && pnpm --filter @esal/ui run build && cd apps/landing && pnpm run build:local
    publishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: VITE_API_URL
        value: https://esalplatform-1.onrender.com
      - key: VITE_SUPABASE_URL
        value: https://ppvkucdspgoeqsxxydxg.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdmt1Y2RzcGdvZXFzeHh5ZHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTkzMzAsImV4cCI6MjA2MzczNTMzMH0.6VVpA6qEcjNPJvPvn0dMh7CUNkNTCYGWsMwb6WS0XGE
      - key: VITE_APP_TITLE
        value: ESAL Platform
      - key: VITE_ENVIRONMENT
        value: production